options:
  debug: false
  disable_spawners_progression: true

all-quests-done:
  daily:
    - "[MESSAGE] &aVous venez de terminer toutes les quêtes daily !"
  weekly:
    - "[MESSAGE] &aVous venez de terminer toutes les quêtes weekly !"
  monthly:
    - "[MESSAGE] &aVous venez de terminer toutes les quêtes monthly !"

cosmetics:
  join-message: "&aVous avez des quêtes disponibles."
  title:
    enabled: true
    fadeIn: 10 # The default number of ticks for the title to fade in.
    stay: 70 # The default number of ticks for the title to stay.
    fadeOut: 20 # The default number of ticks for the title to fade out.
    text: '&bBravo, %player%'
    subtitle: '&aQuête terminée: &7%quest-name%&7 &a!' # Leave this field blank if you do not want a subtitle

quest-files:
  - "quests.yml"

disabled_worlds:
  - "monde_events"

max-quests:
  daily:
    easy: 1
    medium: 1
    difficult: 1
  weekly:
    easy: 2
    medium: 2
    difficult: 2
  monthly:
    easy: 0
    medium: 0
    difficult: 0