quest-files:
  - "quests.yml"

max-quests:
  daily:
    easy: 1
    medium: 1
    difficult: 1
  weekly:
    easy: 2
    medium: 2
    difficult: 2
  monthly:
    easy: 0
    medium: 0
    difficult: 0